 return {
--   'nvim-treesitter/nvim-treesitter',
--   branch = 'main',
--   dependencies = {
--     {
--       'JoosepAlviste/nvim-ts-context-commentstring',
--       config = function()
--         require('ts_context_commentstring').setup {}
--       end,
--     },
--   },
--   build = ':TSUpdate',
--   config = function ()
--     require('nvim-treesitter').setup({
--       ensure_installed = {
--         'bash',
--         'diff',
--         'git_rebase',
--         'javascript',
--         'json',
--         'lua',
--         'pug',
--         'ruby',
--         'toml',
--         'vim',
--         'vue',
--       },
--     })
--   end
 }
